// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.excale.auth.model;

import org.excale.auth.model.Appuser;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Appuser_Roo_Configurable {
    
    declare @type: Appuser: @Configurable;
    
}
